---
layout: post
title:  Impact Evaluation II&#58; Randomized Experiments
date: `r Sys.time()`
published: true
categories: [harvard]
tags: [continuing-eduction]
---

## Preparation for 

- DATE: Tuesday, June 28
- TIME: 11:00 – 12:30 pm and 
- CLASS: Impact Evaluation II: Randomized Experiments
- FACULTY: Dan Levy
- READING: [Randomized Selection Methods](https://www.dropbox.com/s/mc5hha3d0kla5gx/Reading%20-%20Levy_Randomized%20Selection%20Methods%20from%20Impact_Evaluation_in_Practice_49-63.pdf?dl=0)

## Study Questions

**Q1:** What do you see as the main advantages of evaluating a program using a randomized experiment (RCT)?

- it is a fair allocation rule and therefore it shields program managers from potential accusations of favoritism or corruption
- will produce two groups that have a high probability of being statistically identical, as long as the number of potential participants to which we apply the randomized assignment process is sufficiently large
- with a large enough number of observations, the randomized assignment process will produce groups that have statistically equivalent *averages for all their characteristics*
- treatment and comparison groups that are generated through randomized assignment will be similar not only in their observed characteristics but also in their unobserved characteristics
- the comparison group controls for all factors that might also explain the outcome of interest
- the internal validity of an impact evaluation is ensured through the process of randomized assignment of treatment
- allows you to test new or potentially costly programs whose intended and unintended consequences are unknown
- estimating the impact is easy when RCTs are performed correctly $$Impact = Factual - Counterfactual$$


**Q2:** What do you see as the main drawbacks of evaluating a program using a randomized experiment (RCT)

- At higher levels of aggregation (i.e. province level, country level) the sample size may not be not sufficiently large to yield balanced treatment and comparison groups
- chances of spillover can be high when the unit level is low (i.e. households, individuals)
- Treatment and comparison households need to be located sufficiently far from each other to avoid such spillovers


## Notes

Key idea behind RCTs:

- counterfactual
- treatment vs. control
- what is the effect of a program on a given outcome of interest

RCTs also known as:

- Randomized experiments
- randomized trials
- random assignment studies
- social experiments

Non-experimental or quasi-experimental methods:

- differences-in-differences
- statistical matching
- instrumental variables
- regression discontinuity
- interrupted time series

It is important to do a baseline comparison between the control & treatment group to identify if any statistical/practical differences exist

- if there is a difference then resample

Credibility of study based on:

- internal validity: provides causal inference
- external validity: provides generalizability

Random assignment vs. random sampling

- random assignment: relates to internal validity
- random sampling: relates to external validity


Intention to treat vs. Treatment on the treated

- These two measures are often reported in impact evaluations when non-compliance happens
- Important when part of the control group, for some reason, received the treatment

> *"Once a treatment always a treatment; once a control always a control."* - Dan Levy









