---
layout: post
title:  Replication
date: `r Sys.time()`
published: true
categories: [harvard]
tags: [continuing-eduction]
---


## Session

- DATE: Thursday, June 30
- TIME: 9:00 – 10:30 pm
- CLASS: Replication: Integrating Quantitative and Qualitative Research
- INSTRUCTOR: Julie Wilson
- CASE: [MDRC, Toward Reduced Poverty Across Generations: Early Findings from New York City’s Conditional Cash Transfer Program, Executive Summary, pp. ES-1 to ES-18](https://www.dropbox.com/s/v28ojl14in6pnrx/5.1.1_Wilson_MDRC%20Exec%20Summary.pdf?dl=0)
- READING: [Impact Evaluation in Practice. Paul J. Gertler, Sebastian Martinez, Patrick Premand, Laura B. Rawlings, and Christel M. J. Vermeersch. The World Bank, 2011. Pages 14-15: “Efficacy Studies and Effectiveness Studies,” and page 54.](http://siteresources.worldbank.org/EXTHDOFFICE/Resources/5485726- 1295455628620/Impact_Evaluation_in_Practice.pdf)


## Session Notes

Learning *will* take place in an RCT

You can assess in multiple ways:

- 3 groups: Control, Treatment, Process research group
- Process research group is targeted for focus groups, interviews to assess how the processes were implemented. This group is not in the final evaluations so their learning will not influence results
- Or you include the Process research group as a third group and then evaluate the difference in results between control group, treatment group, and then treatment + interview group
- Time-phased assessments: have interviews at set time intervals and then assess the differences in results over time and at those specific intervals

We also need to assess the appropriate time to implement an RCT

- Its important to do pilots prior to RCTs to work out the process kinks and get early assessments of impacts before scaling to an RCT experiment













