# Dependencies
gems:                [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Bradley Boehmke
tagline:             ''
description:         '<img src="https://raw.githubusercontent.com/bradleyboehmke/bradleyboehmke.github.io/master/public/logo.png" height=60 </img>  Follow us on twitter <a href="https://twitter.com/bradleyboehmke">@something</a>'
url:                 http://bradleyboehmke.github.io
baseurl:             ''

