
# Site settings
title: Bradley Boehmke
email: bradleyboehmke@gmail.com
description:         '<div><center><img src="https://raw.githubusercontent.com/bradleyboehmke/bradleyboehmke.github.io/master/public/logo.png" height=80 </img></center></div>  Follow me on twitter <a href="https://twitter.com/bradleyboehmke">@bradleyboehmke</a>'

  
baseurl: "http://bradleyboehmke.github.io" # the subpath of your site, e.g. /blog/
url: "http://bradleyboehmke.github.io" # the base hostname & protocol for your site
twitter_username: bradleyboehmke
github_username:  bradleyboehmke
permalink: /:year/:month/:title.html
excerpt_separator: <!--more-->


# Build settings
markdown: kramdown

# Dependencies
gems:                [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
